validate content size a la ssb-validate
ssbc/ssb-classic pull request #2
Opened 2022-10-10 03:14 UTC by mixmix

# :fire: :bug: 

this module has been letting messages through that other peers consider invalid.
The reference implementation put a cap on the content size, see https://github.com/ssbc/ssb-validate/blob/main/index.js#L111

It appears that this module has not honoured that.
This means that there will likely be messages in the wild which are invalid for some peers and valid for others.

I think we need to consider how to handle that given it might have far reaching + feed-killing effects

2022-10-10 03:24 UTC, mixmix commented
Proposal - think we might want to change out validation to what planetary is doing:
- don't allow writing > 8kb
- allow reading any size

2022-10-10 07:00 UTC, staltz commented
Thanks, well spotted. It seems that this validation was on my mind when I was writing this module, but for some reason I forgot it.

> It appears that this module has not honoured that.

Gladly this module is not yet in production in Manyverse (it will be put this month into production!) so your PR came at the perfect time. I don't believe ssb-classic is used anywhere in production, maybe in Perihelion. Not sure.

The style changes were driving me crazy in this PR, but I realized that that's because we didn't have .prettierrc (we should) and that format-code is run automatically for every commit. I now added the prettierrc config and it should revert some of the code style changes.

2022-10-10 07:11 UTC, staltz requested changes

2022-10-10 07:11 UTC, staltz commented on validation.js
> +        'invalid message: string content must be less than 8192 characters. Current size is ' +
```suggestion
        'invalid message: string content must be at most 8192 characters. Current size is ' +
```

2022-10-10 07:11 UTC, staltz commented on validation.js
> +        'invalid message: encoded content must be less than 8192 characters. Current size is ' +
```suggestion
        'invalid message: encoded content must be at most 8192 characters. Current size is ' +
```

2022-10-10 10:10 UTC, mixmix commented
Please take over and merge if it's patches

2022-10-10 10:47 UTC, staltz commented
@mixmix There's still a test that needs to be moved from https://github.com/ssbc/ssb-db2/pull/394 to here. I won't "take over" this PR because it wasn't my initiative. I had other plans for my day.

2022-10-11 04:25 UTC, mixmix commented
@staltz added tests

2022-10-11 07:45 UTC, merged

2022-10-11 07:45 UTC, staltz commented
Thanks!